/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.Conexao;
import Classes.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Caio
 */
public class TodosOsUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form TodosOsUsuarios
     */
    public TodosOsUsuarios() {
        initComponents();
        
        Connection conn = new Conexao().getConnection();
        try{
            Statement st = conn.createStatement();
            String sql = "SELECT usuarios.id, usuarios.nome, usuarios.email, cargos.nome FROM usuarios JOIN cargos ON usuarios.cargo_id = cargos.id";           

            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()) {
                String id = rs.getString("usuarios.id");
                String nome = rs.getString("usuarios.nome");
                String email = rs.getString("usuarios.email");
                String cargo = rs.getString("cargos.nome");
                
                String tbData[] = {id, nome, email, cargo};
                DefaultTableModel tblModel = (DefaultTableModel)tabelaUsuarios.getModel();
                tblModel.addRow(tbData);
            }
        } catch(SQLException e) {
            System.err.println("Erro ao exibir os usuários: " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        campoPesquisa = new javax.swing.JTextField();
        pesquisaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        btnEditarUsuarios = new javax.swing.JButton();
        btnDeletarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 578));

        jPanel1.setBackground(new java.awt.Color(8, 12, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(907, 94));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuários");

        jButton1.setBackground(new java.awt.Color(8, 12, 70));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(8, 12, 70));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao-voltar (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(351, 351, 351)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        campoPesquisa.setForeground(new java.awt.Color(204, 204, 204));
        campoPesquisa.setText("Digite para pesquisar");

        pesquisaBtn.setForeground(new java.awt.Color(204, 204, 204));
        pesquisaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search icon.png"))); // NOI18N
        pesquisaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaBtnMouseClicked(evt);
            }
        });

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUsuarios);

        btnEditarUsuarios.setForeground(new java.awt.Color(204, 204, 204));
        btnEditarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1976055_edit_edit document_edit file_edited_editing_icon.png"))); // NOI18N
        btnEditarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarUsuariosMouseClicked(evt);
            }
        });

        btnDeletarUsuario.setForeground(new java.awt.Color(204, 204, 204));
        btnDeletarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/211835_trash_icon (1).png"))); // NOI18N
        btnDeletarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletarUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDeletarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 69, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaDeVisualizacao tela = new TelaDeVisualizacao();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDeletarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarUsuarioMouseClicked
        String idString = (String) tabelaUsuarios.getValueAt(tabelaUsuarios.getSelectedRow(), 0);
        int id = Integer.parseInt(idString);
        
        int input = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar esse usuário?");
        if(input == 0) {
            Usuario u = new Usuario();
            u.delete(id);
            JOptionPane.showMessageDialog(null, "Usuário deletado com sucesso!");
            ((DefaultTableModel)tabelaUsuarios.getModel()).removeRow(tabelaUsuarios.getSelectedRow());            
        }
    }//GEN-LAST:event_btnDeletarUsuarioMouseClicked

    private void btnEditarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuariosMouseClicked
        String idString = (String) tabelaUsuarios.getValueAt(tabelaUsuarios.getSelectedRow(), 0);
        int id = Integer.parseInt(idString);
        String nome = (String) tabelaUsuarios.getValueAt(tabelaUsuarios.getSelectedRow(), 1);
        String email = (String) tabelaUsuarios.getValueAt(tabelaUsuarios.getSelectedRow(), 2);
        int input = JOptionPane.showConfirmDialog(null, "Os novos dados serão os dados alterados diretamente na tabela, deseja alterar os dados do usuários selecionado?");
        if(input == 0) {
            Usuario u = new Usuario();
            u.update(id, nome, email);
            JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
        }
    }//GEN-LAST:event_btnEditarUsuariosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaDeVisualizacao tela = new TelaDeVisualizacao();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pesquisaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaBtnMouseClicked
        String campo_pesquisa = campoPesquisa.getText();
        
        Connection conn = new Conexao().getConnection();
        try {        
            DefaultTableModel tblRemove = (DefaultTableModel)tabelaUsuarios.getModel();
            
            if(campo_pesquisa.equals(null)) {
                String sql = "SELECT usuarios.id, usuarios.nome, usuarios.email, cargos.nome FROM usuarios JOIN cargos ON usuarios.cargo_id = cargos.id";
                
                while(tblRemove.getRowCount() > 0) {
                    if (tblRemove.getRowCount() > 0){
                        for (int i=1;i<=tblRemove.getRowCount();i++){
                            tblRemove.removeRow(0);
                        }            
                    }
                }   
                
                PreparedStatement pstm = conn.prepareStatement(sql); 
                ResultSet rs = pstm.executeQuery();
                
                while(rs.next()) {                
                    String id = rs.getString("usuario.id");
                    String nome = rs.getString("usuarios.nome");
                    String email = rs.getString("usuarios.email");
                    String cargo = rs.getString("cargos.nome");

                    String tbData[] = {id, nome, email, cargo};
                    DefaultTableModel tblModel = (DefaultTableModel)tabelaUsuarios.getModel();
                    tblModel.addRow(tbData);
                }                
                
            } else { 
                String sql = "SELECT usuarios.id, usuarios.nome, usuarios.email, cargos.nome FROM usuarios JOIN cargos ON usuarios.cargo_id = cargos.id WHERE usuarios.nome LIKE '" + campo_pesquisa + "%'";                  
                
                while(tblRemove.getRowCount() > 0) {
                    if (tblRemove.getRowCount() > 0){
                        for (int i=1;i<=tblRemove.getRowCount();i++){
                            tblRemove.removeRow(0);
                        }            
                    }
                }
                PreparedStatement pstm = conn.prepareStatement(sql); 
                ResultSet rs = pstm.executeQuery();   
                
                while(rs.next()) {                
                    String id = rs.getString("usuarios.id");
                    String nome = rs.getString("usuarios.nome");
                    String email = rs.getString("usuarios.email");
                    String cargo = rs.getString("cargos.nome");

                    String tbData[] = {id, nome, email, cargo};
                    DefaultTableModel tblModel = (DefaultTableModel)tabelaUsuarios.getModel();
                    tblModel.addRow(tbData);
                }                
            }                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao procurar pelo produto: " + e);            
        }
    }//GEN-LAST:event_pesquisaBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodosOsUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodosOsUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodosOsUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosOsUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodosOsUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarUsuario;
    private javax.swing.JButton btnEditarUsuarios;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisaBtn;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables
}
